[build]
  functions = "netlify/functions"
  publish = "."

# Redirects (optional, but good for API endpoints)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
